definitions:
  routes.CreateUserRequest:
    properties:
      email:
        type: string
      name:
        type: string
    type: object
  routes.LoginRequest:
    properties:
      email:
        type: string
    type: object
  routes.MagicLinkResponse:
    properties:
      magicLink:
        type: string
    type: object
  routes.MagicToken:
    properties:
      magicToken:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/create-user:
    post:
      consumes:
      - application/json
      description: Authenticate user
      parameters:
      - description: User infos
        in: body
        name: UserRequest
        required: true
        schema:
          $ref: '#/definitions/routes.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/routes.MagicLinkResponse'
        "404":
          description: Not Found
      summary: Perform login
      tags:
      - account
  /v1/login:
    post:
      consumes:
      - application/json
      description: Authenticate user
      parameters:
      - description: Email
        in: body
        name: email
        required: true
        schema:
          $ref: '#/definitions/routes.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/routes.MagicLinkResponse'
        "404":
          description: Not Found
      summary: Perform login
      tags:
      - account
  /v1/mobile/magic-link:
    post:
      consumes:
      - application/json
      description: Authenticate user
      parameters:
      - description: token
        in: body
        name: token
        required: true
        schema:
          $ref: '#/definitions/routes.MagicToken'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
      summary: Perform login
      tags:
      - account
swagger: "2.0"
